services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    user: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  gate-simulator:
    image: node:latest
    container_name: gate-simulator
    working_dir: /app
    volumes:
      - ./gate-simulator:/app
    command: npm start
    ports:
      - "9999:9999"
    networks:
      - app-network
    depends_on:
      - mysql
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
