name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run Docker Compose
        run: docker-compose up

      - name: Waiting for container start
        run: sleep 60

      - name: Start SUT
        run: java -jar ./aqa-shop.jar &

      - name: Build with Gradle
        run: ./gradlew test
